---

- name: "clean users"
  user:
    name: "{{ item }}"
    state: absent
    # remove: true
  loop: "{{ clean_users }}"

- name: "clean groups"
  group:
    name: "{{ item }}"
    state: absent
  loop: "{{ clean_groups }}"
